version: '3'

services:
  frontend:
    build:
      context: ./whatShouldWeWear
      dockerfile: Dockerfile
#     image: narumol01/my-frontend_image:1.0
    ports: 
      - '8081:8080'
#     volumes:
